apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: install-automotive-ci-operator
  title: "Install Automotive CI Operator & Create Config CR"
  description: "Installs the Automotive CI Operator from the community-operators catalog, then applies an operator-config CR."
spec:
  owner: coff-team
  type: service

  parameters:
    - title: "Operator Configuration"
      required:
        - operatorChannel
        - subscriptionNamespace
        - operatorConfigCrNamespace
        - operatorConfigCrName
        - operatorConfigCrSpec
      properties:
        operatorChannel:
          title: "Operator Channel"
          type: string
          description: "Subscription channel for the operator"
          default: "alpha"

        subscriptionNamespace:
          title: "Subscription Namespace"
          type: string
          description: "Namespace where Subscription is created (e.g., openshift-operators)"
          default: "openshift-operators"

        operatorConfigCrNamespace:
          title: "Operator Config CR Namespace"
          type: string
          description: "Namespace for the operator-config instance"
          default: "automotive-infra-operator"

        operatorConfigCrName:
          title: "Operator Config CR Name"
          type: string
          description: "Name of your operator-config instance"
          default: "automotive-ci-config"

        operatorConfigCrSpec:
          title: "Operator Config CR Spec"
          type: string
          description: "YAML snippet for your operator-config spec"
          default: |-
            apiVersion: automotiveci.io/v1alpha1
            kind: OperatorConfig
            metadata:
              name: automotive-ci-config
            spec:
              # Insert operator-config fields here
              enableAwesomeFeature: true

  steps:
    - id: install-operator
      name: "Install Automotive CI Operator"
      action: script
      input:
        shell: bash
        script: |
          cat <<EOF > subscription.yaml
          apiVersion: operators.coreos.com/v1alpha1
          kind: Subscription
          metadata:
            name: automotive-ci-subscription
            namespace: {{ parameters.subscriptionNamespace }}
          spec:
            name: automotive-ci
            channel: {{ parameters.operatorChannel }}
            source: community-operators
            sourceNamespace: openshift-marketplace
          EOF

          echo "Installing the Automotive CI Operator using the community-operators catalog..."
          oc apply -f subscription.yaml

    - id: apply-cr
      name: "Apply Operator Config CR"
      action: script
      input:
        shell: bash
        script: |
          echo "{{ parameters.operatorConfigCrSpec }}" > operator-config.yaml

          # Optional: patch the metadata.namespace in the CR if needed:
          # yq e ".metadata.namespace = \"{{ parameters.operatorConfigCrNamespace }}\"" -i operator-config.yaml

          echo "Applying operator-config in namespace {{ parameters.operatorConfigCrNamespace }}..."
          oc apply -n {{ parameters.operatorConfigCrNamespace }} -f operator-config.yaml
